[project]
name = "vcfutil"
version = "0.0.9"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ymat2", email = "ymat2@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
vcfutil = "vcfutil.vcfutil:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.12.12",
]
